### ISSUE TITLE
Parseing OneCrl

### ISSUE THREAD

**Issue by philu-cs** [mozilla/OneCRL-Tools#152]
We currently download and parse the OneCrl list (https://firefox.settings.services.mozilla.com/v1/buckets/blocklists/collections/certificates/records) where we check for an 'issuerName' and 'serialNumber'. Unfortunately this parsing failure  started about 14 days ago and seems to align with the 'Add legacy NSS blocklist' update where these properties seem to be  missing. Is this format intention? 
I apologise if I have raised this issue on the wrong board and if I have could you point me in the right direction.

**Comment by jcjones** [comment]
Obviously I should subscribe to this repo.

As you've undoubtedly found by now, OneCRL long had the ability to block by subject and public-key, we just hadn't had reason to use that mechanism in OneCRL until we migrated the legacy NSS blocklist over.

Basically, both issuer-serial and subject-pubkey constructions are valid, and clients should handle both. Sorry I missed this here, we usually tackle such bugs at Bugzilla in [Core :: Security Block-lists, Allow-lists, and other State](https://bugzilla.mozilla.org/describecomponents.cgi?product=Core&component=Security%20Block-lists%2C%20Allow-lists%2C%20and%20other%20State#Security%20Block-lists%2C%20Allow-lists%2C%20and%20other%20State).
