### ISSUE TITLE
Tag b4bb08372e1e8035e2ec7117031fdd6dd529a5a3 as 'stable'

### ISSUE THREAD

**Issue by mozmark** [mozilla/OneCRL-Tools#159]
We should tag the code as of b4bb08372e1e8035e2ec7117031fdd6dd529a5a3 as stable since TLSCanary depends on one_crl_to_cert_storage and current production data contains entries that will trip earlier versions of this tool up. Happy to this myself but I don't know what else you have depending on this tag.

Let me know what (if anything) uses this tag; if it's just us, I'll take care of it.

@jcjones @tvdmerwe

**Comment by jcjones** [comment]
Tags are intended to be immutable, so I've deleted the `stable` tag and replaced it with a `stable` branch.

There’s now a tag https://github.com/mozilla/OneCRL-Tools/releases/tag/2020-06-05 and that’s what the stable branch points to.
