### ISSUE TITLE
ccadb2OneCRL: Entries with their names decoded to plain text and hexadecimal serials/hashes

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/OneCRL-Tools#170]
Please have the "Entries with their names decoded to plain text and hexadecimal serials/hashes." attachment to the bug provide the same information as coping the "Line delimited issuer/serial pairs" into 
https://mozkeeler.github.io/blocklister/index.html

For Example, in Bug #1666027, the attachment would become the following (note the 'CCADB' info regarding the issuer). It doesn't necessarily need to be the same format, but need to have all of the Issuer info (O, OU, C)
[
  {
    "issuer": {
      "OneCRL": "MFAxJDAiBgNVBAsTG0dsb2JhbFNpZ24gRUNDIFJvb3QgQ0EgLSBSNTETMBEGA1UEChMKR2xvYmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbg==",
      **"CCADB": "/OU=GlobalSign ECC Root CA - R5/O=GlobalSign/CN=GlobalSign"**
    },
    "serial": {
      "OneCRL": "Ae5fInnr9AhpWVIjkw==",
      "CCADB": "01EE5F2279EBF4086959522393"
    }
  },
  {
    "issuer": {
      "OneCRL": "MGAxCzAJBgNVBAYTAk5MMR4wHAYDVQQKDBVTdGFhdCBkZXIgTmVkZXJsYW5kZW4xMTAvBgNVBAMMKFN0YWF0IGRlciBOZWRlcmxhbmRlbiBFViBJbnRlcm1lZGlhaXIgQ0E=",
      **"CCADB": "/C=NL/O=Staat der Nederlanden/CN=Staat der Nederlanden EV Intermediair CA"**
    },
    "serial": {
      "OneCRL": "akWWZTytiy58nyLOsqpnaQ==",
      "CCADB": "6A4596653CAD8B2E7C9F22CEB2AA6769"
    }
  },
  {
    "issuer": {
      "OneCRL": "MF0xCzAJBgNVBAYTAkpQMSUwIwYDVQQKExxTRUNPTSBUcnVzdCBTeXN0ZW1zIENPLixMVEQuMScwJQYDVQQLEx5TZWN1cml0eSBDb21tdW5pY2F0aW9uIFJvb3RDQTI=",
      **"CCADB": "/C=JP/O=SECOM Trust Systems CO.,LTD./OU=Security Communication RootCA2"**
    },
    "serial": {
      "OneCRL": "Irmw1g==",
      "CCADB": "22B9B0D6"
    }
  }
]

**Comment by christopher-henderson** [comment]
Should be covered in #171
