### ISSUE TITLE
Make integration tests run offline

### ISSUE THREAD

**Issue by jcjones** [mozilla/OneCRL-Tools#44]
oneCRL.go's LoadJSONFromURL has a TODO that it should take a Reader; this would help write offline integration tests (like PR #42)

Line in question: https://github.com/mozmark/OneCRL-Tools/blob/12ad599192d7b6cf0c40348a4f87b07c63e2e02b/oneCRL/oneCRL.go#L261

**Comment by cr** [comment]
Ideally one would just run `go test -t` in the main directory, and have that trigger everything that's required, including the integration test of #42. I couldn't really figure out how to properly set up the repo for Go testing within my allotted timebox, mostly because I am not familiar with the way Go runs tests and how to write proper binary integration tests in Go, but this would certainly be the way forward.

**Comment by cr** [comment]
`go test -t` would be the solution that runs offline quite naturally, and ideally it would be able to pull in all test dependencies, too. The integration test of #42 can also run offline, but it's a slightly nasty manual process:

```bash
$ cd OneCRL-Tools
$ export GOPATH=/tmp/go
$ mkdir -p $GOPATH/src/github.com/mozmark/
$ ln -s $PWD $GOPATH/src/github.com/mozmark/
$ go get gopkg.in/yaml.v2 golang.org/x/crypto/ssh/terminal
$ go install github.com/mozmark/OneCRL-Tools/oneCRL2RevocationsTxt
$ tests/integration.sh
```

**Comment by jcjones** [comment]
As-is though, it always reads from a URL, which makes it impractical to make it a known-answer-test. This issue should be to permit it to read from a Reader, and thus we can make the integration test more precise, instead of relying on goodness heuristics. That's all I mean. :)

**Comment by cr** [comment]
How would that look like in practice for testing the binaries? A command line argument that internally makes it pass a reader to `LoadJSONFromURL()` that returns static test data?

**Comment by jcjones** [comment]
You'd make invoking it look more like https://github.com/mozmark/OneCRL-Tools/blob/12ad599192d7b6cf0c40348a4f87b07c63e2e02b/salesforce2OneCRL/salesforce2OneCRL.go#L59-L81 , where the binary could be run against static data or a URL. But if we do it via a Go test, we just test the `salesforce` package rather than the `salesforce2OneCRL` command. (Preferably, we do some of both)

**Comment by cr** [comment]
... and then make that conditional to a command line option. Makes sense.

> But if we do it via a Go test, we just test the salesforce package rather than the salesforce2OneCRL command. (Preferably, we do some of both)

That's precisely the issue we as consumers of `oneCRL2RevocationsTxt` ran into, and what #42 is trying to help with. The package might have tested fine, but the command wrapper broke silently.
